services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"  # Maps local port 5000 to container port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000  # Ensure .NET listens on port 5000
      - ConnectionStrings__DefaultConnection=Host=long-dust-739.internal;Database=events_api;Username=postgres;Password=uCuZLuc5aXVfcj5
    depends_on:
      - db
    networks:
      - event-network



  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: event-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - event-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d event-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - event-network

networks:
  event-network:

volumes:
  db-data: