services:
  backend:
    build: 
      context: .  # Assumes Dockerfile is in the same directory
      dockerfile: Dockerfile  # Make sure you have a Dockerfile for your .NET project
    restart: always
    ports:
      - "5189:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=event-db;Username=admin;Password=admin123
    depends_on:
      - db
    networks:
      - event-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: event-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - event-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d event-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - event-network

networks:
  event-network:

volumes:
  db-data: