version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"  # Maps local port 5000 to container port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000  # Ensure .NET listens on port 5000
      - ConnectionStrings__DefaultConnection=Host=pg-1975442c-lovekilledtshepo-0388.j.aivencloud.com;Port=28024;Database=defaultdb;Username=avnadmin;Password=AVNS_PJt3l2E8NE25C3k4sGl;SSL Mode=Require;Trust Server Certificate=true
    networks:
      - event-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - event-network

networks:
  event-network: