# fly.toml app configuration file generated for events-api-blue-wave-3744 on 2024-11-11T07:25:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'events-api-blue-wave-3744'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[
env
]
  ConnectionStrings__DefaultConnection = "Host=pg-1975442c-lovekilledtshepo-0388.j.aivencloud.com;Port=28024;Database=defaultdb;Username=avnadmin;Password=AVNS_PJt3l2E8NE25C3k4sGl;SSL Mode=Require;Trust Server Certificate=true"
